### ISSUE TITLE
How can you interpret "len_q", "len_k", "len_v" in MultiHeadAttention()?

### ISSUE THREAD

**Issue by lukysummer** [jadore801120/attention-is-all-you-need-pytorch#109]
Thank you greatly for your code. I just have a question about Q, K, V's dimension parameters:

is len_q = len_k = len_v = (# of elements in input sequence) basically?
or is there a case where any of len_q, k, or v < (# of elements in input sequence)?
(i.e. only a subset of input elements are used to calculate Q, K, V matrices?)

Thank you.

**Comment by jadore801120** [comment]
@lukysummer 
`len_k` will always equals to `len_v`, because `v` and `k` come from same sentence and that is the designer's intension to separate it into two.
In self attn, `q` is also comes from the same sentence as `k` and `v`, so in this case, the three lengths will be the same.
In dec-enc attn, `q` comes from target sentence, and `k`, `v` come from source sentence, so they are not necessary to be the same.
Please take a look on the newest code.
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/Layers.py#L39-L40

Hope this helps.
