### ISSUE TITLE
How is it possible to use the code for text generation, not translation

### ISSUE THREAD

**Issue by Hannabrahman** [jadore801120/attention-is-all-you-need-pytorch#116]
Hi,

I realized in the readme you explained how to pass wmt data, preprocess that and run train.py.

How is it possible to run train.py on a dataset with similar source and target language. source and target being in separate text file.

**Comment by dksehdals216** [comment]
The title is confusing. Do you want to run the same translation model with a different dataset or use the transformer for text generation?

**Comment by jadore801120** [comment]
I guess you are talking about train on the different data sources.
Since I switched to the `torchtext` lib, the following code will be in `torchtext` style.
Assume your src and trg files are `./YourData/train.src` and `./YourData/train.trg`.
For more details, please check [preprocess.py](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/preprocess.py).
```python
from torchtext.datasets import TranslationDataset
# `fields` need to be defined.
files_path_prefix = './YourData/train'
train = TranslationDataset(
        fields=fields,
        path=files_path_prefix,
        exts=('.src', '.trg'))
```
