### ISSUE TITLE
About Layernorm

### ISSUE THREAD

**Issue by BUCTwangkun** [jadore801120/attention-is-all-you-need-pytorch#142]
I think there is a problem in your code about using layer_norm.

In the forword function of MultiHeadAttention, you just layer norm the q vector at the begining of the function. I think you should layer norm (residual + attention(q,k,v,mask))(just ignoring the feed forword and dropout)

**Comment by egornevezhin** [comment]
> I think there is a problem in your code about using layer_norm.
> 
> In the forword function of MultiHeadAttention, you just layer norm the q vector at the begining of the function. I think you should layer norm (residual + attention(q,k,v,mask))(just ignoring the feed forword and dropout)

Yes, you are right.  Layer norm is not calculated correctly, because of [this](https://discuss.pytorch.org/t/nan-in-layer-normalization/13846/9) and [this](https://github.com/pytorch/pytorch/issues/4320). I found [another](https://github.com/leviswind/pytorch-transformer/blob/9aaf4cd5a5f88671a06ef1d7fe617984027c586f/modules.py#L256) realisation of layer normalization it this [repo](https://github.com/leviswind/pytorch-transformer). I was started used this and have no problem with layer normalization.

**Comment by jadore801120** [comment]
Hi, @BUCTwangkun @tony2037, sorry for the confusion. I have fixed it.
Hi @egornevezhin, if it is possible, please share more to me. Thanks!
