### ISSUE TITLE
Training on Custom Data

### ISSUE THREAD

**Issue by kevaday** [jadore801120/attention-is-all-you-need-pytorch#145]
Hello,

I was wondering if it is possible to train the transformer on a **custom dataset** that does not have to be downloaded, without me having to go through a lot of the code and changing it. For example, I have my own dataset that consists of **modern english** phrases and the targets are **old english/Shakespearean phrases**. Is it possible to **preprocess** this kind of data in order to train the model on it?

Thanks

**Comment by jadore801120** [comment]
Hi @kevaday , sorry for the late reply.
For preprocessing, it depends on the way you want to handle the old english.
If you just want to split the sentence into tokens by whitespace, then you don't need to worry about it.
If you want to preprocess with lemmatization or something in the preprocessing stage, I am not sure if the modern nlp tools (nltk, spaCy) have special methods on handling old english or not.

On the other hand, if you use the subword tokenization methods (bpe, etc.), the you can easily get your preprocessing done, since no grammar concepts involved in this kind of methods, and apply transformer to the tokenized sentences.

Hope this helps.
Reopen this issue freely if needed.
Thanks.
