### ISSUE TITLE
Incorrect implementation?

### ISSUE THREAD

**Issue by weilueluo** [jadore801120/attention-is-all-you-need-pytorch#177]
Hi I think there are at least two differences between this implementation and the one describe in the paper:

1.
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/132907dd272e2cc92e3c10e6c4e783a87ff8893d/transformer/Modules.py#L17

I think in the original implementation, the matrix multiplication is done before dividing the temperature (which refers to `d_k` in suppose), does it make a difference? Or just me bad at my math?

2.
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/132907dd272e2cc92e3c10e6c4e783a87ff8893d/transformer/SubLayers.py#L39

I think the `view` here should be `view(sz_b, n_head, len_q, d_k)` instead, otherwise, we will be multiplying with the wrong dimension in this code again:
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/132907dd272e2cc92e3c10e6c4e783a87ff8893d/transformer/Modules.py#L17

May I know if I missed something here?

**Comment by ducnx** [comment]
1. Since the temperature is a scalar, the order of operations does not make any difference.
2. At this [line](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/132907dd272e2cc92e3c10e6c4e783a87ff8893d/transformer/SubLayers.py#L44) the transpose function is applied, so shape of `q` becomes `(sz_b, n_head, len_q, d_k)`. There's no problem here.
Why `transpose` but not directly `view` like your suggestion? It's to avoid batch interference. You can run this following example and see the difference.
```
import torch
q = torch.tensor([
    [0.1, 0.1, 0.1, 0.1, 0.1, 0.1], 
    [0.2, 0.2, 0.2, 0.2, 0.2, 0.2], 
    [1, 1, 1, 1, 1, 1],
    [2, 2, 2, 2, 2, 2],
]).unsqueeze(0)
print(q)
right = q.view(1, 4, 2, 3).transpose(1, 2)
print(right)
wrong = q.view(1, 2, 4, 3)
print(wrong)
```
Right: the first head contains all of the first 3 numbers.
Wrong: the first head contains all numbers < 1.

**Comment by weilueluo** [comment]
@ducnx I see, thank you so much for explaining it to me! I understand my mistake now!
