### ISSUE TITLE
Batch Beam Search Problem

### ISSUE THREAD

**Issue by ZiJianZhao** [jadore801120/attention-is-all-you-need-pytorch#21]
In the [Beam.py-L30-L31](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/Beam.py#L30-L31):
```
self.next_ys = [self.tt.LongTensor(size).fill_(Constants.PAD)]
self.next_ys[0][0] = Constants.BOS
```
It seems that only the top hypothesis get "BOS" as start while all other hypothesis get "PAD" as start. Why don't all the hypothesis get "BOS" as start? 
And in the [Beam.py-L65-L68](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/Beam.py#L65-L68):
```
        # End condition is when top-of-beam is EOS.
        if self.next_ys[-1][0] == Constants.EOS:
            self.done = True
            self.all_scores.append(self.scores)
```
you set that end condition is when top-of-beam is "EOS". Why top-of-beam instead of all-of-beam?

**Comment by HsuWanTing** [comment]
For the first question, since all the hypotheses will start with "BOS", the predictions of the first time step will be the same. So in [Beam.py-L49](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/Beam.py#L49), it will only take the output of the first beam (`word_lk` has shape (beam_size * vocab_size), so `word_lk[0]` means the first beam).
```
if len(self.prev_ks) > 0:
     beam_lk = word_lk + self.scores.unsqueeze(1).expand_as(word_lk)
else:
     beam_lk = word_lk[0]
```

**Comment by ZiJianZhao** [comment]
Thanks for your reply.

**Comment by jadore801120** [comment]
Hi @ZiJianZhao and @HsuWanTing,
Thanks for the discussion and clarification!
Let me close this issue.

Yu-Hsiang
